/**
 * The root file that combines all of our types
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
import Recipe from './Recipe';
import Ingredient from './Ingredient';

const Query = /* GraphQL */`
  type Query {
    recipes(vegetarian: Boolean, ingredient: String): [Recipe!]!
    ingredients: [Ingredient!]
    recipe(id: ID!): Recipe!
  }
`;

const Schema = /* GraphQL */`
  schema {
    query: Query
  }
`;

export default [Schema, Query, Recipe, Ingredient];
