/**
 * The root file that combines all of our resolvers
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
import { getRecipes, getRecipe } from '../models/Recipe';
import {
  getIngredient,
  getIngredients
} from '../models/Ingredient';

export default {
  Recipe: {
    ingredients: ({ ingredients }) => {
      return Promise.all(
        ingredients.map(ingredient => getIngredient(ingredient))
      );
    }
  },
  Query: {
    recipes: (_, args) => {
      return getRecipes(args);
    },
    ingredients: (_, args) => getIngredients(args),
    recipe: (_, {id}) => getRecipe(id),
  },
};
